[project]
name = "misbot"
version = "0.3.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Bohdan Stratila", email = "googlobody@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "aiosqlite>=0.22.1",
    "alembic>=1.18.1",
    "cryptography>=50.0.0",
    "fastapi[standard]>=0.128.0",
    "ijson>=3.5.1",
    "pydantic-settings>=2.12.0",
    "pyjwt>=2.13.0",
    "python-telegram-bot[webhooks]>=22.8",
    "sqlalchemy[asyncio]>=2.0.45",
    "uvicorn[standard]>=0.40.0",
]

[project.scripts]
run-server = "misbot:server"


[build-system]
requires = ["uv_build>=0.11.28,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.14.11",
    "pytest>=7.0",
    "pytest-asyncio>=0.21",
]
test = [
    "pytest>=7.0",
    "pytest-asyncio>=0.21",
]


[tool.ruff.lint]
extend-select = ["I"]
