"""add type to channel

Revision ID: a4b4a64736ee
Revises: d78a3befc8dd
Create Date: 2026-03-08 21:41:10.501791

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a4b4a64736ee"
down_revision: Union[str, Sequence[str], None] = "d78a3befc8dd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("channels", sa.Column("type", sa.String(), nullable=True))
    op.execute("UPDATE channels SET type = 'logger' WHERE type IS NULL")
    with op.batch_alter_table("channels") as batch_op:
        batch_op.alter_column("type", nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("channels", "type")
    # ### end Alembic commands ###
