"""Use time sessions

Revision ID: b5f4471cfa73
Revises: ff9b196aaf18
Create Date: 2026-03-07 15:28:14.885276

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b5f4471cfa73"
down_revision: Union[str, Sequence[str], None] = "ff9b196aaf18"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    dialect = conn.dialect.name
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("time_spent")

    op.rename_table("players", "players_old")
    op.create_table(
        "players",
        sa.Column(
            "id",
            sa.Uuid(),
            primary_key=True,
            nullable=False,
        ),
        sa.Column("seen", sa.DateTime(), nullable=False),
    )
    op.execute(
        "INSERT INTO players (id, seen) SELECT id{} , seen FROM players_old".format(
            "::uuid" if dialect == "postgresql" else ""
        )
    )
    op.create_table(
        "time_sessions",
        sa.Column("session_id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("joined_at", sa.DateTime(), nullable=True),
        sa.Column("quit_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("session_id"),
    )

    op.drop_table("players_old")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse: Change players.id from UUID to VARCHAR using table-rebuild pattern
    conn = op.get_bind()
    dialect = conn.dialect.name

    op.rename_table("players", "players_new")
    op.create_table(
        "players",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("seen", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.execute(
        "INSERT INTO players (id, seen) SELECT id{} , seen FROM players_new".format(
            "::varchar" if dialect == "postgresql" else ""
        )
    )
    op.drop_table("players_new")
    op.create_table(
        "time_spent",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("player_id", sa.String(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("time_sessions")
    # ### end Alembic commands ###
