"""Add type col to channels table

Revision ID: 5f4176ddd09d
Revises: 8f870c47446b
Create Date: 2026-08-27 15:36:50.522844

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f4176ddd09d"
down_revision: Union[str, Sequence[str], None] = "8f870c47446b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("channels", sa.Column("type", sa.String(), nullable=True))

    # Populate existing rows.
    op.execute("UPDATE channels SET type = 'logger'")

    # Make the column non-nullable after all existing rows have a value.
    with op.batch_alter_table("channels") as batch_op:
        batch_op.alter_column(
            "type",
            existing_type=sa.String(),
            nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("channels", "type")
    # ### end Alembic commands ###
