"""Add nickname col to the players table

Revision ID: 8f870c47446b
Revises: b5f4471cfa73
Create Date: 2026-08-23 19:36:30.716082

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f870c47446b"
down_revision: Union[str, Sequence[str], None] = "b5f4471cfa73"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("players", sa.Column("nickname", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("players", "nickname")
    # ### end Alembic commands ###
