"""add nickname to players

Revision ID: d78a3befc8dd
Revises: b5f4471cfa73
Create Date: 2026-03-08 10:14:20.345513

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d78a3befc8dd"
down_revision: Union[str, Sequence[str], None] = "b5f4471cfa73"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("players", sa.Column("nickname", sa.String(), nullable=True))
    op.drop_column("players", "seen")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("players", sa.Column("seen", sa.DATETIME(), nullable=False))
    op.drop_column("players", "nickname")
    # ### end Alembic commands ###
