import re
from enum import StrEnum
from functools import lru_cache
from pathlib import Path
from typing import Annotated

from pydantic import AfterValidator, BaseModel, Field, SecretStr
from pydantic_settings import BaseSettings, SettingsConfigDict


class RuntimeEnvironment(StrEnum):
    DEV = "dev"
    PROD = "prod"


class ManagedChannelType(StrEnum):
    """Managed channel roles.

    ``LOGGER`` handles join and quit messages from the FastAPI app endpoints.

    ``REGULAR`` handles stats and echoes messages from the admin user
    identified by ``ChannelSettings.admin_user_id`` in the Telegram bot
    handlers.
    """

    LOGGER = "logger"
    REGULAR = "regular"


def validate_item_format(value: str) -> str:
    """Extract type and check against ManagedChannelType"""
    pattern = r"^-?\d+-([a-zA-Z]+)$"
    match = re.match(pattern, value)

    if not match:
        raise ValueError(f"Invalid format '{value}'")

    extracted_type = match.group(1)
    valid_types = [member.value for member in ManagedChannelType]
    if extracted_type not in valid_types:
        raise ValueError(
            f"Invalid type '{extracted_type}'. Must be one of: {', '.join(valid_types)}"
        )

    return value


ManagedChannelIdWithType = Annotated[str, AfterValidator(validate_item_format)]


class DatabaseSettings(BaseModel):
    sql_echo: bool = Field(
        default=False,
        description="SQLAlchemy verbose query log mode",
    )
    db_file: Path

    @property
    def sqlite_connection_string(self):
        return f"sqlite+aiosqlite:///{self.db_file.as_posix()}"


class TelegramBotSettings(BaseModel):
    token: SecretStr = Field(
        default=...,
        description="A Telegram Bot API token is generated by @BotFather.",
    )
    webhook_secret_token: SecretStr = Field(
        default=...,
        description="Secret used to secure the webhook and validate Telegram requests",
    )
    webhook_url: str = Field(
        default=...,
        description="HTTPS webhook URL for Telegram requests",
    )


class ChannelSettings(BaseModel):
    admin_user_id: int
    managed_chat_ids: list[ManagedChannelIdWithType]

    def get_managed_ids(self, type: ManagedChannelType) -> list[int]:
        result = []
        for mcid in self.managed_chat_ids:
            chat_id, chat_type = mcid.rsplit("-", maxsplit=1)
            if chat_type == type.value:
                result.append(int(chat_id))
        return result

    @property
    def all_managed_chat_ids(self) -> list[int]:
        return [int(mcid.rsplit("-", maxsplit=1)[0]) for mcid in self.managed_chat_ids]


class AuthorizationSettings(BaseModel):
    issuer: str
    audience: str
    token_url: str
    jwks_url: str


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        # .env has priority over .dev.env
        env_file=(".env.dev", ".env"),
        env_prefix="MISBOT_",
        env_nested_delimiter="__",
    )

    environment: RuntimeEnvironment
    telegram_bot: TelegramBotSettings
    database: DatabaseSettings
    channel: ChannelSettings
    auth: AuthorizationSettings


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    return Settings()
