import os
from enum import StrEnum
from functools import lru_cache

from pydantic import BaseModel, Field, FilePath, SecretStr
from pydantic_settings import BaseSettings, SettingsConfigDict


class RuntimeEnvironment(StrEnum):
    DEV = "dev"
    PROD = "prod"


class DatabaseSettings(BaseModel):
    sql_echo: bool = Field(
        default=False,
        description="SQLAlchemy verbose query log mode",
    )
    db_file: FilePath

    @property
    def sqlite_connection_string(self):
        return f"sqlite+aiosqlite:///{self.db_file.as_posix()}"


class TelegramBotSettings(BaseModel):
    token: SecretStr = Field(
        default=...,
        description="A Telegram Bot API token is generated by @BotFather.",
    )
    webhook_secret_token: SecretStr = Field(
        default=...,
        description="Secret used to secure the webhook and validate Telegram requests",
    )
    webhook_url: str = Field(
        default=...,
        description="HTTPS webhook URL for Telegram requests",
    )


class SecuritySettings(BaseModel):
    secret_key: SecretStr
    algorithm: str
    access_token_expire_minutes: int = 30


class ChannelSettings(BaseModel):
    admin_user_id: int
    managed_chat_ids: list[int]


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        # .env has priority over .dev.env
        env_file=(".dev.env ", ".env")
    )

    environment: RuntimeEnvironment
    telegram_bot: TelegramBotSettings
    security: SecuritySettings
    database: DatabaseSettings
    channel: ChannelSettings


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    return Settings()
