name: CI pipeline for application deployment

on:
    push:
        branches:
            - feat/quadlet-deploy

jobs:
    test:
        uses: ./.github/workflows/test.yml

    build-and-push:
        permissions:
            contents: read
            packages: write
        needs: test
        uses: ./.github/workflows/build-and-push.yml
        secrets: inherit
