name: Test
on:
    workflow_call:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            # - name: Checkout
            #   uses: actions/checkout@v4

            # - name: Set up Docker Buildx
            #   uses: docker/setup-buildx-action@v4
            
            # - name: Build image for testing
            #   uses: docker/build-push-action@v6
            #   with:
            #       context: .
            #       file: Containerfile
            #       target: prod
            #       load: true
            #       push: false
            #       tags: ghcr.io/${{ github.repository }}:ci-test
            #       cache-from: type=gha
            #       cache-to: type=gha,mode=max

            - name: Pytest run
              run: echo "Success"
            # TODO: Fix image
            #   run: |
            #       docker run --rm --entrypoint "/bin/bash" \
            #        --mount=type=bind,source=$(pwd),target=/app  \
            #        ghcr.io/${{ github.repository }}:ci-test -c "/opt/venv/bin/pytest"
